name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.5.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .  
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy backend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
